// Code generated by cmd/gen-tools from openapi.yaml + admin-tools.yaml. DO NOT EDIT.

package tools

import (
	"context"
	"net/http"
	"net/url"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/shukiv/jabali-mcp/internal/client"
)

func registerAdminRead(s *mcp.Server, reg *client.Registry) {
	{
		type AdminListUsersIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_list_users", Description: "List all panel users (admin)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminListUsersIn) (*mcp.CallToolResult, any, error) {
				path := "/admin/users"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type AdminGetSettingsIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_get_settings", Description: "Read server-wide settings (admin)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminGetSettingsIn) (*mcp.CallToolResult, any, error) {
				path := "/admin/settings"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
}

func registerAdminWrite(s *mcp.Server, reg *client.Registry) {
	{
		type AdminCreateUserIn struct {
			panelArg
			dryRunArg
			Email    string `json:"email" jsonschema:"email"`
			IsAdmin  *bool  `json:"is_admin,omitempty" jsonschema:"is admin"`
			Password string `json:"password" jsonschema:"password"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_create_user", Description: "Create a tenant user (admin)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminCreateUserIn) (*mcp.CallToolResult, any, error) {
				if r := vMinLen("password", in.Password, 12); r != nil {
					return r, nil, nil
				}
				path := "/admin/users"
				body := map[string]any{}
				body["email"] = in.Email
				if in.IsAdmin != nil {
					body["is_admin"] = *in.IsAdmin
				}
				body["password"] = in.Password
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type AdminUpdateSettingsIn struct {
			panelArg
			dryRunArg
			DefaultDnsTtl int    `json:"default_dns_ttl,omitempty" jsonschema:"Server-wide default TTL for new DNS records (seconds)."`
			Hostname      string `json:"hostname,omitempty" jsonschema:"hostname"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_update_settings", Description: "Update server-wide settings (admin)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminUpdateSettingsIn) (*mcp.CallToolResult, any, error) {
				if in.DefaultDnsTtl != 0 {
					if r := vMin("default_dns_ttl", in.DefaultDnsTtl, 60); r != nil {
						return r, nil, nil
					}
					if r := vMax("default_dns_ttl", in.DefaultDnsTtl, 86400); r != nil {
						return r, nil, nil
					}
				}
				path := "/admin/settings"
				body := map[string]any{}
				if in.DefaultDnsTtl != 0 {
					body["default_dns_ttl"] = in.DefaultDnsTtl
				}
				if in.Hostname != "" {
					body["hostname"] = in.Hostname
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type AdminRunUpdatesIn struct {
			panelArg
			dryRunArg
			confirmArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_run_updates", Description: "Trigger `jabali update` (admin)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminRunUpdatesIn) (*mcp.CallToolResult, any, error) {
				path := "/admin/updates/run"
				preview := "Destructive, irreversible — Trigger `jabali update` (admin). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type AdminRenewSslIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_renew_ssl", Description: "Force-renew a domain's certificate (admin)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminRenewSslIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl/renew"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type AdminRetrySslIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_retry_ssl", Description: "Retry a failed certificate issuance (admin)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminRetrySslIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl/retry"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
}
