// Code generated by cmd/gen-tools from openapi.yaml + tools.yaml. DO NOT EDIT.

package tools

import (
	"context"
	"net/http"
	"net/url"
	"strconv"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/shukiv/jabali-mcp/internal/client"
)

func registerRead(s *mcp.Server, reg *client.Registry) {
	{
		type ListDomainsIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_domains", Description: "List your domains", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDomainsIn) (*mcp.CallToolResult, any, error) {
				path := "/domains"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetDomainIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_domain", Description: "get_domain", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetDomainIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListDnsRecordsIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_dns_records", Description: "List records in a zone", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDnsRecordsIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/dns/records"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListMailboxesIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_mailboxes", Description: "list_mailboxes", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListMailboxesIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/mailboxes"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListForwardersIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_forwarders", Description: "list_forwarders", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListForwardersIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/forwarders"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListApplicationsIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_applications", Description: "List installed apps", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListApplicationsIn) (*mcp.CallToolResult, any, error) {
				path := "/applications"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListDatabasesIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_databases", Description: "list_databases", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDatabasesIn) (*mcp.CallToolResult, any, error) {
				path := "/databases"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListBackupsIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_backups", Description: "List your snapshots", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListBackupsIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListApiTokensIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_api_tokens", Description: "List your API tokens", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListApiTokensIn) (*mcp.CallToolResult, any, error) {
				path := "/me/api-tokens"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListMailLogsIn struct {
			panelArg
			Limit     int    `json:"limit,omitempty" jsonschema:"max entries"`
			Offset    int    `json:"offset,omitempty" jsonschema:"offset"`
			Sender    string `json:"sender,omitempty" jsonschema:"filter by sender address"`
			Recipient string `json:"recipient,omitempty" jsonschema:"filter by recipient address"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_mail_logs", Description: "List recent mail log entries for your domains (delivered/failed/queued)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListMailLogsIn) (*mcp.CallToolResult, any, error) {
				path := "/mail/logs"
				q := url.Values{}
				if in.Limit != 0 {
					q.Set("limit", strconv.Itoa(in.Limit))
				}
				if in.Offset != 0 {
					q.Set("offset", strconv.Itoa(in.Offset))
				}
				if in.Sender != "" {
					q.Set("sender", in.Sender)
				}
				if in.Recipient != "" {
					q.Set("recipient", in.Recipient)
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type TailWebLogIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			LogType  string `json:"log_type" jsonschema:"one of: access, error"`
			Lines    int    `json:"lines,omitempty" jsonschema:"how many trailing lines"`
		}
		schema := inferSchema[TailWebLogIn]()
		schema.Properties["log_type"].Enum = enumVals("access", "error")
		schema.Properties["lines"].Minimum = f64(1)
		schema.Properties["lines"].Maximum = f64(2000)
		mcp.AddTool(s, &mcp.Tool{Name: "tail_web_log", Description: "Tail a domain's nginx access or error log (last N lines, snapshot)", Annotations: roAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in TailWebLogIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("log_type", in.LogType, []string{"access", "error"}); r != nil {
					return r, nil, nil
				}
				if in.Lines != 0 {
					if r := vMin("lines", in.Lines, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("lines", in.Lines, 2000); r != nil {
						return r, nil, nil
					}
				}
				path := "/logs/tail"
				q := url.Values{}
				q.Set("domain_id", in.DomainId)
				q.Set("log_type", in.LogType)
				if in.Lines != 0 {
					q.Set("lines", strconv.Itoa(in.Lines))
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetSslStatusIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_ssl_status", Description: "SSL certificate status for a domain", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetSslStatusIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetDomainWhoisIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_domain_whois", Description: "WHOIS lookup for a domain (registrar, expiry, name servers)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetDomainWhoisIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/whois"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetDomainBandwidthIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			From     string `json:"from,omitempty" jsonschema:"start date YYYY-MM-DD (default 30 days ago)"`
			To       string `json:"to,omitempty" jsonschema:"end date YYYY-MM-DD (default today)"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_domain_bandwidth", Description: "Bandwidth usage for a domain (bytes + requests, daily series)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetDomainBandwidthIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/bandwidth"
				q := url.Values{}
				if in.From != "" {
					q.Set("from", in.From)
				}
				if in.To != "" {
					q.Set("to", in.To)
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type WhoamiIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "whoami", Description: "The calling account — id, email, package, limits", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in WhoamiIn) (*mcp.CallToolResult, any, error) {
				path := "/me"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetDiskUsageIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_disk_usage", Description: "Disk usage breakdown — files, mail, databases vs quota", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetDiskUsageIn) (*mcp.CallToolResult, any, error) {
				path := "/me/disk-usage"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListActivityIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_activity", Description: "Your recent activity (audit events, newest first)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListActivityIn) (*mcp.CallToolResult, any, error) {
				path := "/me/activity"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListCronJobsIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_cron_jobs", Description: "List your cron jobs", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListCronJobsIn) (*mcp.CallToolResult, any, error) {
				path := "/cron"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetCronJobIn struct {
			panelArg
			CronId string `json:"cron_id" jsonschema:"the cron's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_cron_job", Description: "Get a cron job", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetCronJobIn) (*mcp.CallToolResult, any, error) {
				path := "/cron/" + url.PathEscape(in.CronId)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetCronLogIn struct {
			panelArg
			CronId string `json:"cron_id" jsonschema:"the cron's ULID"`
			Lines  int    `json:"lines,omitempty" jsonschema:"trailing lines to return (default 50)"`
		}
		schema := inferSchema[GetCronLogIn]()
		schema.Properties["lines"].Minimum = f64(1)
		schema.Properties["lines"].Maximum = f64(500)
		mcp.AddTool(s, &mcp.Tool{Name: "get_cron_log", Description: "Read a cron job's recent log output", Annotations: roAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetCronLogIn) (*mcp.CallToolResult, any, error) {
				if in.Lines != 0 {
					if r := vMin("lines", in.Lines, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("lines", in.Lines, 500); r != nil {
						return r, nil, nil
					}
				}
				path := "/cron/" + url.PathEscape(in.CronId) + "/log"
				q := url.Values{}
				if in.Lines != 0 {
					q.Set("lines", strconv.Itoa(in.Lines))
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListAppCatalogIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_app_catalog", Description: "App catalog — every kind the panel can one-click install", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListAppCatalogIn) (*mcp.CallToolResult, any, error) {
				path := "/applications/registry"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetApplicationIn struct {
			panelArg
			ApplicationId string `json:"application_id" jsonschema:"the application's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_application", Description: "Get an installed app (status, version, URL)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetApplicationIn) (*mcp.CallToolResult, any, error) {
				path := "/applications/" + url.PathEscape(in.ApplicationId)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetDatabaseIn struct {
			panelArg
			DatabasId string `json:"databas_id" jsonschema:"the databas's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_database", Description: "Get a database (engine, size, grants)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetDatabaseIn) (*mcp.CallToolResult, any, error) {
				path := "/databases/" + url.PathEscape(in.DatabasId)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListDatabaseUsersIn struct {
			panelArg
			Page     int `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int `json:"page_size,omitempty" jsonschema:"results per page (default 20)"`
		}
		schema := inferSchema[ListDatabaseUsersIn]()
		schema.Properties["page"].Minimum = f64(1)
		schema.Properties["page_size"].Minimum = f64(1)
		schema.Properties["page_size"].Maximum = f64(200)
		mcp.AddTool(s, &mcp.Tool{Name: "list_database_users", Description: "List your database users", Annotations: roAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDatabaseUsersIn) (*mcp.CallToolResult, any, error) {
				if in.Page != 0 {
					if r := vMin("page", in.Page, 1); r != nil {
						return r, nil, nil
					}
				}
				if in.PageSize != 0 {
					if r := vMin("page_size", in.PageSize, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("page_size", in.PageSize, 200); r != nil {
						return r, nil, nil
					}
				}
				path := "/database-users"
				q := url.Values{}
				if in.Page != 0 {
					q.Set("page", strconv.Itoa(in.Page))
				}
				if in.PageSize != 0 {
					q.Set("page_size", strconv.Itoa(in.PageSize))
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetMailboxIn struct {
			panelArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_mailbox", Description: "Get a mailbox (address, quota, flags)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetMailboxIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetAutoresponderIn struct {
			panelArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_autoresponder", Description: "Get a mailbox's autoresponder (vacation reply)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetAutoresponderIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId) + "/autoresponder"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetBackupManifestIn struct {
			panelArg
			BackupId string `json:"backup_id" jsonschema:"the backup's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_backup_manifest", Description: "List a snapshot's contents (manifest; only for succeeded backups)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetBackupManifestIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups/" + url.PathEscape(in.BackupId) + "/manifest"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListSshKeysIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_ssh_keys", Description: "List your SSH keys (name + fingerprint; never the key material)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListSshKeysIn) (*mcp.CallToolResult, any, error) {
				path := "/ssh-keys"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetPhpSettingsIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_php_settings", Description: "Effective PHP settings for a domain (version, limits)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetPhpSettingsIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/php-settings"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListPhpVersionsIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_php_versions", Description: "PHP runtimes installed on the server", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListPhpVersionsIn) (*mcp.CallToolResult, any, error) {
				path := "/php/versions"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListFilesIn struct {
			panelArg
			Path string `json:"path" jsonschema:"directory path inside your home, e.g. /public_html"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_files", Description: "List a directory in your home (name, size, mtime per entry)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListFilesIn) (*mcp.CallToolResult, any, error) {
				path := "/files"
				q := url.Values{}
				q.Set("path", in.Path)
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type PreviewFileIn struct {
			panelArg
			Path string `json:"path" jsonschema:"file path inside your home"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "preview_file", Description: "Read a file's contents (max 1 MiB; may expose secrets such as wp-config.php — handle with care)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in PreviewFileIn) (*mcp.CallToolResult, any, error) {
				path := "/files/preview"
				q := url.Values{}
				q.Set("path", in.Path)
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
}

func registerWrite(s *mcp.Server, reg *client.Registry) {
	{
		type CreateDomainIn struct {
			panelArg
			dryRunArg
			Name string `json:"name" jsonschema:"e.g. example.com"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_domain", Description: "Add a domain", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateDomainIn) (*mcp.CallToolResult, any, error) {
				path := "/domains"
				body := map[string]any{}
				body["name"] = in.Name
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type UpdateDomainIn struct {
			panelArg
			dryRunArg
			DomainId        string `json:"domain_id" jsonschema:"the domain's ULID"`
			IsEnabled       *bool  `json:"is_enabled,omitempty" jsonschema:"Enable or disable the site (vhost stays, serving stops)."`
			RedirectAllTo   string `json:"redirect_all_to,omitempty" jsonschema:"Redirect the whole site to this URL (clearing a redirect is done in the panel UI)."`
			RedirectAllType string `json:"redirect_all_type,omitempty" jsonschema:"HTTP status for the site-wide redirect."`
			SslMode         string `json:"ssl_mode,omitempty" jsonschema:"TLS mode: le = Let's Encrypt, self = self-signed, none = HTTP only. (custom/shared are managed via the panel's SSL settings.)"`
			TempUrlEnabled  *bool  `json:"temp_url_enabled,omitempty" jsonschema:"Toggle the preview (temp) URL for this domain."`
			WebmailEnabled  *bool  `json:"webmail_enabled,omitempty" jsonschema:"Toggle the webmail subdomain for this domain."`
		}
		schema := inferSchema[UpdateDomainIn]()
		schema.Properties["redirect_all_type"].Enum = enumVals("301", "302", "307", "308")
		schema.Properties["ssl_mode"].Enum = enumVals("le", "self", "none")
		mcp.AddTool(s, &mcp.Tool{Name: "update_domain", Description: "Update a domain's settings (partial — absent fields are left untouched)", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in UpdateDomainIn) (*mcp.CallToolResult, any, error) {
				if in.RedirectAllType != "" {
					if r := vEnum("redirect_all_type", in.RedirectAllType, []string{"301", "302", "307", "308"}); r != nil {
						return r, nil, nil
					}
				}
				if in.SslMode != "" {
					if r := vEnum("ssl_mode", in.SslMode, []string{"le", "self", "none"}); r != nil {
						return r, nil, nil
					}
				}
				path := "/domains/" + url.PathEscape(in.DomainId)
				body := map[string]any{}
				if in.IsEnabled != nil {
					body["is_enabled"] = *in.IsEnabled
				}
				if in.RedirectAllTo != "" {
					body["redirect_all_to"] = in.RedirectAllTo
				}
				if in.RedirectAllType != "" {
					body["redirect_all_type"] = in.RedirectAllType
				}
				if in.SslMode != "" {
					body["ssl_mode"] = in.SslMode
				}
				if in.TempUrlEnabled != nil {
					body["temp_url_enabled"] = *in.TempUrlEnabled
				}
				if in.WebmailEnabled != nil {
					body["webmail_enabled"] = *in.WebmailEnabled
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type CreateDnsRecordIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			Content  string `json:"content" jsonschema:"e.g. 203.0.113.5"`
			Name     string `json:"name" jsonschema:"e.g. vpn"`
			Priority int    `json:"priority,omitempty" jsonschema:"priority"`
			Ttl      int    `json:"ttl,omitempty" jsonschema:"Omit to use server-wide default (Server Settings → DNS)."`
			Type     string `json:"type" jsonschema:"one of: A, AAAA, CNAME, MX, TXT, SRV, CAA, NS"`
		}
		schema := inferSchema[CreateDnsRecordIn]()
		schema.Properties["type"].Enum = enumVals("A", "AAAA", "CNAME", "MX", "TXT", "SRV", "CAA", "NS")
		mcp.AddTool(s, &mcp.Tool{Name: "create_dns_record", Description: "Create a record", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateDnsRecordIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("type", in.Type, []string{"A", "AAAA", "CNAME", "MX", "TXT", "SRV", "CAA", "NS"}); r != nil {
					return r, nil, nil
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/dns/records"
				body := map[string]any{}
				body["content"] = in.Content
				body["name"] = in.Name
				if in.Priority != 0 {
					body["priority"] = in.Priority
				}
				if in.Ttl != 0 {
					body["ttl"] = in.Ttl
				}
				body["type"] = in.Type
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type UpdateDnsRecordIn struct {
			panelArg
			dryRunArg
			RecordId  string `json:"record_id" jsonschema:"the record's ULID"`
			Content   string `json:"content,omitempty" jsonschema:"e.g. 203.0.113.99"`
			IsEnabled *bool  `json:"is_enabled,omitempty" jsonschema:"is enabled"`
			Priority  int    `json:"priority,omitempty" jsonschema:"priority"`
			Ttl       int    `json:"ttl,omitempty" jsonschema:"ttl"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "update_dns_record", Description: "Update a record", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in UpdateDnsRecordIn) (*mcp.CallToolResult, any, error) {
				path := "/dns/records/" + url.PathEscape(in.RecordId)
				body := map[string]any{}
				if in.Content != "" {
					body["content"] = in.Content
				}
				if in.IsEnabled != nil {
					body["is_enabled"] = *in.IsEnabled
				}
				if in.Priority != 0 {
					body["priority"] = in.Priority
				}
				if in.Ttl != 0 {
					body["ttl"] = in.Ttl
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type CreateMailboxIn struct {
			panelArg
			dryRunArg
			DomainId  string `json:"domain_id" jsonschema:"the domain's ULID"`
			LocalPart string `json:"local_part" jsonschema:"e.g. alice"`
			Password  string `json:"password" jsonschema:"password"`
			QuotaMb   int    `json:"quota_mb" jsonschema:"e.g. 1024"`
		}
		schema := inferSchema[CreateMailboxIn]()
		schema.Properties["password"].MinLength = iptr(12)
		mcp.AddTool(s, &mcp.Tool{Name: "create_mailbox", Description: "create_mailbox", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateMailboxIn) (*mcp.CallToolResult, any, error) {
				if r := vMinLen("password", in.Password, 12); r != nil {
					return r, nil, nil
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/mailboxes"
				body := map[string]any{}
				body["local_part"] = in.LocalPart
				body["password"] = in.Password
				body["quota_mb"] = in.QuotaMb
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type CreateForwarderIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			Dest     string `json:"dest" jsonschema:"e.g. alice@example.com"`
			Source   string `json:"source" jsonschema:"e.g. sales@example.com"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_forwarder", Description: "create_forwarder", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateForwarderIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/forwarders"
				body := map[string]any{}
				body["dest"] = in.Dest
				body["source"] = in.Source
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type CreateBackupIn struct {
			panelArg
			dryRunArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_backup", Description: "Trigger an on-demand backup", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateBackupIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type InstallApplicationIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"domain id"`
			Kind     string `json:"kind" jsonschema:"one of: wordpress, joomla, drupal, moodle, ghost, opencart, prestashop, magento, drupal10, mediawiki, nextcloud, mautic, suitecrm, dolibarr, processmaker"`
			Path     string `json:"path,omitempty" jsonschema:"Install path under doc-root."`
		}
		schema := inferSchema[InstallApplicationIn]()
		schema.Properties["kind"].Enum = enumVals("wordpress", "joomla", "drupal", "moodle", "ghost", "opencart", "prestashop", "magento", "drupal10", "mediawiki", "nextcloud", "mautic", "suitecrm", "dolibarr", "processmaker")
		mcp.AddTool(s, &mcp.Tool{Name: "install_application", Description: "Install an app (WordPress, Joomla, etc.)", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in InstallApplicationIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("kind", in.Kind, []string{"wordpress", "joomla", "drupal", "moodle", "ghost", "opencart", "prestashop", "magento", "drupal10", "mediawiki", "nextcloud", "mautic", "suitecrm", "dolibarr", "processmaker"}); r != nil {
					return r, nil, nil
				}
				path := "/applications"
				body := map[string]any{}
				body["domain_id"] = in.DomainId
				body["kind"] = in.Kind
				if in.Path != "" {
					body["path"] = in.Path
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type CreateDatabaseIn struct {
			panelArg
			dryRunArg
			Engine string `json:"engine" jsonschema:"one of: mysql, postgres"`
			Name   string `json:"name" jsonschema:"e.g. myapp_prod"`
		}
		schema := inferSchema[CreateDatabaseIn]()
		schema.Properties["engine"].Enum = enumVals("mysql", "postgres")
		mcp.AddTool(s, &mcp.Tool{Name: "create_database", Description: "Create a database", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateDatabaseIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("engine", in.Engine, []string{"mysql", "postgres"}); r != nil {
					return r, nil, nil
				}
				path := "/databases"
				body := map[string]any{}
				body["engine"] = in.Engine
				body["name"] = in.Name
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type EnableSslIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "enable_ssl", Description: "Enable SSL — issue a Let's Encrypt certificate for the domain", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in EnableSslIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type CreateCronJobIn struct {
			panelArg
			dryRunArg
			Command  string `json:"command" jsonschema:"shell command to run (as your user)"`
			Enabled  *bool  `json:"enabled,omitempty" jsonschema:"enabled"`
			Name     string `json:"name" jsonschema:"job label"`
			Schedule string `json:"schedule" jsonschema:"cron schedule expression, e.g. '*/15 * * * *'"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_cron_job", Description: "Create a cron job", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateCronJobIn) (*mcp.CallToolResult, any, error) {
				path := "/cron"
				body := map[string]any{}
				body["command"] = in.Command
				if in.Enabled != nil {
					body["enabled"] = *in.Enabled
				}
				body["name"] = in.Name
				body["schedule"] = in.Schedule
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type UpdateCronJobIn struct {
			panelArg
			dryRunArg
			CronId   string `json:"cron_id" jsonschema:"the cron's ULID"`
			Command  string `json:"command,omitempty" jsonschema:"shell command to run (as your user)"`
			Enabled  *bool  `json:"enabled,omitempty" jsonschema:"enable or disable the job"`
			Name     string `json:"name,omitempty" jsonschema:"job label"`
			Schedule string `json:"schedule,omitempty" jsonschema:"cron schedule expression, e.g. '*/15 * * * *'"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "update_cron_job", Description: "Update a cron job (partial — absent fields are left untouched)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in UpdateCronJobIn) (*mcp.CallToolResult, any, error) {
				path := "/cron/" + url.PathEscape(in.CronId)
				body := map[string]any{}
				if in.Command != "" {
					body["command"] = in.Command
				}
				if in.Enabled != nil {
					body["enabled"] = *in.Enabled
				}
				if in.Name != "" {
					body["name"] = in.Name
				}
				if in.Schedule != "" {
					body["schedule"] = in.Schedule
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type RunCronJobIn struct {
			panelArg
			dryRunArg
			CronId string `json:"cron_id" jsonschema:"the cron's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "run_cron_job", Description: "Run a cron job immediately (409 if the job is disabled)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in RunCronJobIn) (*mcp.CallToolResult, any, error) {
				path := "/cron/" + url.PathEscape(in.CronId) + "/run-now"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type CreateDatabaseUserIn struct {
			panelArg
			dryRunArg
			Engine   string `json:"engine,omitempty" jsonschema:"database engine (default mariadb)"`
			Username string `json:"username" jsonschema:"login name (your account prefix is enforced)"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_database_user", Description: "Create a database user (returns its password once)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateDatabaseUserIn) (*mcp.CallToolResult, any, error) {
				path := "/database-users"
				body := map[string]any{}
				if in.Engine != "" {
					body["engine"] = in.Engine
				}
				body["username"] = in.Username
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type GrantDatabaseAccessIn struct {
			panelArg
			dryRunArg
			DatabaseUserId string `json:"database_user_id" jsonschema:"the database_user's ULID"`
			DatabaseId     string `json:"database_id" jsonschema:"the database's ULID"`
			GrantLevel     string `json:"grant_level" jsonschema:"rw = read-write, ro = read-only"`
		}
		schema := inferSchema[GrantDatabaseAccessIn]()
		schema.Properties["grant_level"].Enum = enumVals("rw", "ro")
		mcp.AddTool(s, &mcp.Tool{Name: "grant_database_access", Description: "Grant a database user access to one of your databases", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GrantDatabaseAccessIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("grant_level", in.GrantLevel, []string{"rw", "ro"}); r != nil {
					return r, nil, nil
				}
				path := "/database-users/" + url.PathEscape(in.DatabaseUserId) + "/grants"
				body := map[string]any{}
				body["database_id"] = in.DatabaseId
				body["grant_level"] = in.GrantLevel
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type UpdateMailboxIn struct {
			panelArg
			dryRunArg
			MailboxId   string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
			DisplayName string `json:"display_name,omitempty" jsonschema:"display name shown in webmail"`
			IsDisabled  *bool  `json:"is_disabled,omitempty" jsonschema:"disable login + delivery for this mailbox"`
			QuotaBytes  int    `json:"quota_bytes,omitempty" jsonschema:"mailbox quota in bytes (min 16 MiB)"`
			SendOnly    *bool  `json:"send_only,omitempty" jsonschema:"mailbox may send but not receive"`
		}
		schema := inferSchema[UpdateMailboxIn]()
		schema.Properties["quota_bytes"].Minimum = f64(16777216)
		mcp.AddTool(s, &mcp.Tool{Name: "update_mailbox", Description: "Update a mailbox (partial — absent fields are left untouched)", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in UpdateMailboxIn) (*mcp.CallToolResult, any, error) {
				if in.QuotaBytes != 0 {
					if r := vMin("quota_bytes", in.QuotaBytes, 16777216); r != nil {
						return r, nil, nil
					}
				}
				path := "/mailboxes/" + url.PathEscape(in.MailboxId)
				body := map[string]any{}
				if in.DisplayName != "" {
					body["display_name"] = in.DisplayName
				}
				if in.IsDisabled != nil {
					body["is_disabled"] = *in.IsDisabled
				}
				if in.QuotaBytes != 0 {
					body["quota_bytes"] = in.QuotaBytes
				}
				if in.SendOnly != nil {
					body["send_only"] = *in.SendOnly
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type SetAutoresponderIn struct {
			panelArg
			dryRunArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
			Enabled   bool   `json:"enabled" jsonschema:"turn the autoresponder on or off"`
			FromDate  string `json:"from_date,omitempty" jsonschema:"start (RFC 3339, e.g. 2026-08-10T00:00:00Z); omit for immediate"`
			HtmlBody  string `json:"html_body,omitempty" jsonschema:"HTML reply body"`
			Subject   string `json:"subject,omitempty" jsonschema:"reply subject"`
			TextBody  string `json:"text_body,omitempty" jsonschema:"plain-text reply body"`
			ToDate    string `json:"to_date,omitempty" jsonschema:"end (RFC 3339); omit for open-ended"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "set_autoresponder", Description: "Set a mailbox's autoresponder (vacation reply)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in SetAutoresponderIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId) + "/autoresponder"
				body := map[string]any{}
				body["enabled"] = in.Enabled
				if in.FromDate != "" {
					body["from_date"] = in.FromDate
				}
				if in.HtmlBody != "" {
					body["html_body"] = in.HtmlBody
				}
				if in.Subject != "" {
					body["subject"] = in.Subject
				}
				if in.TextBody != "" {
					body["text_body"] = in.TextBody
				}
				if in.ToDate != "" {
					body["to_date"] = in.ToDate
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPut, path, body})
			})
	}
	{
		type AddSshKeyIn struct {
			panelArg
			dryRunArg
			Name      string `json:"name" jsonschema:"key label, e.g. laptop"`
			PublicKey string `json:"public_key" jsonschema:"OpenSSH public key line (ed25519 or RSA >= 2048 bits)"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "add_ssh_key", Description: "Add an SSH public key for SFTP/SSH access", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AddSshKeyIn) (*mcp.CallToolResult, any, error) {
				path := "/ssh-keys"
				body := map[string]any{}
				body["name"] = in.Name
				body["public_key"] = in.PublicKey
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type UpdatePhpSettingsIn struct {
			panelArg
			dryRunArg
			DomainId             string `json:"domain_id" jsonschema:"the domain's ULID"`
			PhpMaxExecutionTime  int    `json:"php_max_execution_time,omitempty" jsonschema:"script time limit, seconds"`
			PhpMaxInputTime      int    `json:"php_max_input_time,omitempty" jsonschema:"input parsing time limit, seconds"`
			PhpMaxInputVars      int    `json:"php_max_input_vars,omitempty" jsonschema:"max request input variables"`
			PhpMemoryLimit       string `json:"php_memory_limit,omitempty" jsonschema:"digits + optional K/M/G suffix, e.g. 256M"`
			PhpPostMaxSize       string `json:"php_post_max_size,omitempty" jsonschema:"digits + optional K/M/G suffix, e.g. 64M"`
			PhpUploadMaxFilesize string `json:"php_upload_max_filesize,omitempty" jsonschema:"digits + optional K/M/G suffix, e.g. 64M"`
			PhpVersion           string `json:"php_version,omitempty" jsonschema:"e.g. 8.3 — must be installed on the server (see list_php_versions); changes the pool shared by ALL your domains"`
		}
		schema := inferSchema[UpdatePhpSettingsIn]()
		schema.Properties["php_max_execution_time"].Minimum = f64(1)
		schema.Properties["php_max_execution_time"].Maximum = f64(86400)
		schema.Properties["php_max_input_time"].Minimum = f64(1)
		schema.Properties["php_max_input_time"].Maximum = f64(86400)
		schema.Properties["php_max_input_vars"].Minimum = f64(1)
		schema.Properties["php_max_input_vars"].Maximum = f64(86400)
		mcp.AddTool(s, &mcp.Tool{Name: "update_php_settings", Description: "Update a domain's PHP settings (partial — absent fields are left untouched)", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in UpdatePhpSettingsIn) (*mcp.CallToolResult, any, error) {
				if in.PhpMaxExecutionTime != 0 {
					if r := vMin("php_max_execution_time", in.PhpMaxExecutionTime, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("php_max_execution_time", in.PhpMaxExecutionTime, 86400); r != nil {
						return r, nil, nil
					}
				}
				if in.PhpMaxInputTime != 0 {
					if r := vMin("php_max_input_time", in.PhpMaxInputTime, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("php_max_input_time", in.PhpMaxInputTime, 86400); r != nil {
						return r, nil, nil
					}
				}
				if in.PhpMaxInputVars != 0 {
					if r := vMin("php_max_input_vars", in.PhpMaxInputVars, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("php_max_input_vars", in.PhpMaxInputVars, 86400); r != nil {
						return r, nil, nil
					}
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/php-settings"
				body := map[string]any{}
				if in.PhpMaxExecutionTime != 0 {
					body["php_max_execution_time"] = in.PhpMaxExecutionTime
				}
				if in.PhpMaxInputTime != 0 {
					body["php_max_input_time"] = in.PhpMaxInputTime
				}
				if in.PhpMaxInputVars != 0 {
					body["php_max_input_vars"] = in.PhpMaxInputVars
				}
				if in.PhpMemoryLimit != "" {
					body["php_memory_limit"] = in.PhpMemoryLimit
				}
				if in.PhpPostMaxSize != "" {
					body["php_post_max_size"] = in.PhpPostMaxSize
				}
				if in.PhpUploadMaxFilesize != "" {
					body["php_upload_max_filesize"] = in.PhpUploadMaxFilesize
				}
				if in.PhpVersion != "" {
					body["php_version"] = in.PhpVersion
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type DeleteDomainIn struct {
			panelArg
			dryRunArg
			confirmArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_domain", Description: "delete_domain", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteDomainIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId)
				preview := "Destructive, irreversible — delete_domain. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteDnsRecordIn struct {
			panelArg
			dryRunArg
			confirmArg
			RecordId string `json:"record_id" jsonschema:"the record's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_dns_record", Description: "Delete a record", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteDnsRecordIn) (*mcp.CallToolResult, any, error) {
				path := "/dns/records/" + url.PathEscape(in.RecordId)
				preview := "Destructive, irreversible — Delete a record. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteMailboxIn struct {
			panelArg
			dryRunArg
			confirmArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_mailbox", Description: "delete_mailbox", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteMailboxIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId)
				preview := "Destructive, irreversible — delete_mailbox. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type SetMailboxPasswordIn struct {
			panelArg
			dryRunArg
			confirmArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
			Password  string `json:"password" jsonschema:"password"`
		}
		schema := inferSchema[SetMailboxPasswordIn]()
		schema.Properties["password"].MinLength = iptr(12)
		mcp.AddTool(s, &mcp.Tool{Name: "set_mailbox_password", Description: "Change mailbox password", Annotations: destructiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in SetMailboxPasswordIn) (*mcp.CallToolResult, any, error) {
				if r := vMinLen("password", in.Password, 12); r != nil {
					return r, nil, nil
				}
				path := "/mailboxes/" + url.PathEscape(in.MailboxId) + "/password"
				body := map[string]any{}
				body["password"] = in.Password
				preview := "Destructive, irreversible — Change mailbox password. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPut, path, body})
			})
	}
	{
		type RestoreBackupIn struct {
			panelArg
			dryRunArg
			confirmArg
			BackupId string `json:"backup_id" jsonschema:"the backup's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "restore_backup", Description: "Restore a snapshot", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in RestoreBackupIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups/" + url.PathEscape(in.BackupId) + "/restore"
				preview := "Destructive, irreversible — Restore a snapshot. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type DisableSslIn struct {
			panelArg
			dryRunArg
			confirmArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "disable_ssl", Description: "Disable SSL — revoke the domain's certificate and stop serving HTTPS", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DisableSslIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl"
				preview := "Destructive, irreversible — Disable SSL — revoke the domain's certificate and stop serving HTTPS. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteCronJobIn struct {
			panelArg
			dryRunArg
			confirmArg
			CronId string `json:"cron_id" jsonschema:"the cron's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_cron_job", Description: "Delete a cron job", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteCronJobIn) (*mcp.CallToolResult, any, error) {
				path := "/cron/" + url.PathEscape(in.CronId)
				preview := "Destructive, irreversible — Delete a cron job. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteApplicationIn struct {
			panelArg
			dryRunArg
			confirmArg
			ApplicationId string `json:"application_id" jsonschema:"the application's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_application", Description: "Uninstall an app and remove its files (async)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteApplicationIn) (*mcp.CallToolResult, any, error) {
				path := "/applications/" + url.PathEscape(in.ApplicationId)
				preview := "Destructive, irreversible — Uninstall an app and remove its files (async). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteDatabaseIn struct {
			panelArg
			dryRunArg
			confirmArg
			DatabasId string `json:"databas_id" jsonschema:"the databas's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_database", Description: "Drop a database and all its data", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteDatabaseIn) (*mcp.CallToolResult, any, error) {
				path := "/databases/" + url.PathEscape(in.DatabasId)
				preview := "Destructive, irreversible — Drop a database and all its data. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteDatabaseUserIn struct {
			panelArg
			dryRunArg
			confirmArg
			DatabaseUserId string `json:"database_user_id" jsonschema:"the database_user's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_database_user", Description: "Delete a database user (revokes all its grants)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteDatabaseUserIn) (*mcp.CallToolResult, any, error) {
				path := "/database-users/" + url.PathEscape(in.DatabaseUserId)
				preview := "Destructive, irreversible — Delete a database user (revokes all its grants). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type RevokeDatabaseAccessIn struct {
			panelArg
			dryRunArg
			confirmArg
			DatabaseUserGrantId string `json:"database_user_grant_id" jsonschema:"the database_user_grant's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "revoke_database_access", Description: "Revoke one database grant (keeps the user)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in RevokeDatabaseAccessIn) (*mcp.CallToolResult, any, error) {
				path := "/database-user-grants/" + url.PathEscape(in.DatabaseUserGrantId)
				preview := "Destructive, irreversible — Revoke one database grant (keeps the user). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type RotateDatabasePasswordIn struct {
			panelArg
			dryRunArg
			confirmArg
			DatabaseUserId string `json:"database_user_id" jsonschema:"the database_user's ULID"`
			NewPassword    string `json:"new_password" jsonschema:"the new password to set"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "rotate_database_password", Description: "Rotate a database user's password (returns the new password once)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in RotateDatabasePasswordIn) (*mcp.CallToolResult, any, error) {
				path := "/database-users/" + url.PathEscape(in.DatabaseUserId) + "/rotate-password"
				body := map[string]any{}
				body["new_password"] = in.NewPassword
				preview := "Destructive, irreversible — Rotate a database user's password (returns the new password once). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type DeleteAutoresponderIn struct {
			panelArg
			dryRunArg
			confirmArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_autoresponder", Description: "Remove a mailbox's autoresponder", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteAutoresponderIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId) + "/autoresponder"
				preview := "Destructive, irreversible — Remove a mailbox's autoresponder. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type RotateMailboxPasswordIn struct {
			panelArg
			dryRunArg
			confirmArg
			MailboxId   string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
			NewPassword string `json:"new_password,omitempty" jsonschema:"omit to auto-generate a strong password"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "rotate_mailbox_password", Description: "Rotate a mailbox password (returns the new password once)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in RotateMailboxPasswordIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId) + "/rotate-password"
				body := map[string]any{}
				if in.NewPassword != "" {
					body["new_password"] = in.NewPassword
				}
				preview := "Destructive, irreversible — Rotate a mailbox password (returns the new password once). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type DeleteBackupIn struct {
			panelArg
			dryRunArg
			confirmArg
			BackupId string `json:"backup_id" jsonschema:"the backup's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_backup", Description: "Delete a snapshot (forgets + prunes its data)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteBackupIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups/" + url.PathEscape(in.BackupId)
				preview := "Destructive, irreversible — Delete a snapshot (forgets + prunes its data). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteSshKeyIn struct {
			panelArg
			dryRunArg
			confirmArg
			SshKeyId string `json:"ssh_key_id" jsonschema:"the ssh_key's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_ssh_key", Description: "Remove an SSH key (revokes its access)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteSshKeyIn) (*mcp.CallToolResult, any, error) {
				path := "/ssh-keys/" + url.PathEscape(in.SshKeyId)
				preview := "Destructive, irreversible — Remove an SSH key (revokes its access). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
}
