// Code generated by cmd/gen-tools from openapi.yaml + tools.yaml. DO NOT EDIT.

package tools

import (
	"context"
	"net/http"
	"net/url"
	"strconv"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/shukiv/jabali-mcp/internal/client"
)

func registerRead(s *mcp.Server, reg *client.Registry) {
	{
		type ListDomainsIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_domains", Description: "List your domains", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDomainsIn) (*mcp.CallToolResult, any, error) {
				path := "/domains"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type GetDomainIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "get_domain", Description: "get_domain", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in GetDomainIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListDnsRecordsIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_dns_records", Description: "List records in a zone", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDnsRecordsIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/dns/records"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListMailboxesIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_mailboxes", Description: "list_mailboxes", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListMailboxesIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/mailboxes"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListForwardersIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_forwarders", Description: "list_forwarders", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListForwardersIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/forwarders"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListApplicationsIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_applications", Description: "List installed apps", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListApplicationsIn) (*mcp.CallToolResult, any, error) {
				path := "/applications"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListDatabasesIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_databases", Description: "list_databases", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListDatabasesIn) (*mcp.CallToolResult, any, error) {
				path := "/databases"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListBackupsIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_backups", Description: "List your snapshots", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListBackupsIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListApiTokensIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_api_tokens", Description: "List your API tokens", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListApiTokensIn) (*mcp.CallToolResult, any, error) {
				path := "/me/api-tokens"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type ListMailLogsIn struct {
			panelArg
			Limit     int    `json:"limit,omitempty" jsonschema:"max entries"`
			Offset    int    `json:"offset,omitempty" jsonschema:"offset"`
			Sender    string `json:"sender,omitempty" jsonschema:"filter by sender address"`
			Recipient string `json:"recipient,omitempty" jsonschema:"filter by recipient address"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "list_mail_logs", Description: "List recent mail log entries for your domains (delivered/failed/queued)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in ListMailLogsIn) (*mcp.CallToolResult, any, error) {
				path := "/mail/logs"
				q := url.Values{}
				if in.Limit != 0 {
					q.Set("limit", strconv.Itoa(in.Limit))
				}
				if in.Offset != 0 {
					q.Set("offset", strconv.Itoa(in.Offset))
				}
				if in.Sender != "" {
					q.Set("sender", in.Sender)
				}
				if in.Recipient != "" {
					q.Set("recipient", in.Recipient)
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type TailWebLogIn struct {
			panelArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			LogType  string `json:"log_type" jsonschema:"one of: access, error"`
			Lines    int    `json:"lines,omitempty" jsonschema:"how many trailing lines"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "tail_web_log", Description: "Tail a domain's nginx access or error log (last N lines, snapshot)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in TailWebLogIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("log_type", in.LogType, []string{"access", "error"}); r != nil {
					return r, nil, nil
				}
				if in.Lines != 0 {
					if r := vMin("lines", in.Lines, 1); r != nil {
						return r, nil, nil
					}
					if r := vMax("lines", in.Lines, 2000); r != nil {
						return r, nil, nil
					}
				}
				path := "/logs/tail"
				q := url.Values{}
				q.Set("domain_id", in.DomainId)
				q.Set("log_type", in.LogType)
				if in.Lines != 0 {
					q.Set("lines", strconv.Itoa(in.Lines))
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
}

func registerWrite(s *mcp.Server, reg *client.Registry) {
	{
		type CreateDomainIn struct {
			panelArg
			dryRunArg
			Name string `json:"name" jsonschema:"e.g. example.com"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_domain", Description: "Add a domain", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateDomainIn) (*mcp.CallToolResult, any, error) {
				path := "/domains"
				body := map[string]any{}
				body["name"] = in.Name
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type CreateDnsRecordIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			Content  string `json:"content" jsonschema:"e.g. 203.0.113.5"`
			Name     string `json:"name" jsonschema:"e.g. vpn"`
			Priority int    `json:"priority,omitempty" jsonschema:"priority"`
			Ttl      int    `json:"ttl,omitempty" jsonschema:"Omit to use server-wide default (Server Settings → DNS)."`
			Type     string `json:"type" jsonschema:"one of: A, AAAA, CNAME, MX, TXT, SRV, CAA, NS"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_dns_record", Description: "Create a record", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateDnsRecordIn) (*mcp.CallToolResult, any, error) {
				if r := vEnum("type", in.Type, []string{"A", "AAAA", "CNAME", "MX", "TXT", "SRV", "CAA", "NS"}); r != nil {
					return r, nil, nil
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/dns/records"
				body := map[string]any{}
				body["content"] = in.Content
				body["name"] = in.Name
				if in.Priority != 0 {
					body["priority"] = in.Priority
				}
				if in.Ttl != 0 {
					body["ttl"] = in.Ttl
				}
				body["type"] = in.Type
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type UpdateDnsRecordIn struct {
			panelArg
			dryRunArg
			RecordId  string `json:"record_id" jsonschema:"the record's ULID"`
			Content   string `json:"content,omitempty" jsonschema:"e.g. 203.0.113.99"`
			IsEnabled *bool  `json:"is_enabled,omitempty" jsonschema:"is enabled"`
			Priority  int    `json:"priority,omitempty" jsonschema:"priority"`
			Ttl       int    `json:"ttl,omitempty" jsonschema:"ttl"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "update_dns_record", Description: "Update a record", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in UpdateDnsRecordIn) (*mcp.CallToolResult, any, error) {
				path := "/dns/records/" + url.PathEscape(in.RecordId)
				body := map[string]any{}
				if in.Content != "" {
					body["content"] = in.Content
				}
				if in.IsEnabled != nil {
					body["is_enabled"] = *in.IsEnabled
				}
				if in.Priority != 0 {
					body["priority"] = in.Priority
				}
				if in.Ttl != 0 {
					body["ttl"] = in.Ttl
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type CreateMailboxIn struct {
			panelArg
			dryRunArg
			DomainId  string `json:"domain_id" jsonschema:"the domain's ULID"`
			LocalPart string `json:"local_part" jsonschema:"e.g. alice"`
			Password  string `json:"password" jsonschema:"password"`
			QuotaMb   int    `json:"quota_mb" jsonschema:"e.g. 1024"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_mailbox", Description: "create_mailbox", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateMailboxIn) (*mcp.CallToolResult, any, error) {
				if r := vMinLen("password", in.Password, 12); r != nil {
					return r, nil, nil
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/mailboxes"
				body := map[string]any{}
				body["local_part"] = in.LocalPart
				body["password"] = in.Password
				body["quota_mb"] = in.QuotaMb
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type CreateForwarderIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
			Dest     string `json:"dest" jsonschema:"e.g. alice@example.com"`
			Source   string `json:"source" jsonschema:"e.g. sales@example.com"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_forwarder", Description: "create_forwarder", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateForwarderIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId) + "/forwarders"
				body := map[string]any{}
				body["dest"] = in.Dest
				body["source"] = in.Source
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type CreateBackupIn struct {
			panelArg
			dryRunArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "create_backup", Description: "Trigger an on-demand backup", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in CreateBackupIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type DeleteDomainIn struct {
			panelArg
			dryRunArg
			confirmArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_domain", Description: "delete_domain", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteDomainIn) (*mcp.CallToolResult, any, error) {
				path := "/domains/" + url.PathEscape(in.DomainId)
				preview := "Destructive, irreversible — delete_domain. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteDnsRecordIn struct {
			panelArg
			dryRunArg
			confirmArg
			RecordId string `json:"record_id" jsonschema:"the record's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_dns_record", Description: "Delete a record", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteDnsRecordIn) (*mcp.CallToolResult, any, error) {
				path := "/dns/records/" + url.PathEscape(in.RecordId)
				preview := "Destructive, irreversible — Delete a record. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type DeleteMailboxIn struct {
			panelArg
			dryRunArg
			confirmArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "delete_mailbox", Description: "delete_mailbox", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in DeleteMailboxIn) (*mcp.CallToolResult, any, error) {
				path := "/mailboxes/" + url.PathEscape(in.MailboxId)
				preview := "Destructive, irreversible — delete_mailbox. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodDelete, path, nil})
			})
	}
	{
		type SetMailboxPasswordIn struct {
			panelArg
			dryRunArg
			confirmArg
			MailboxId string `json:"mailbox_id" jsonschema:"the mailbox's ULID"`
			Password  string `json:"password" jsonschema:"password"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "set_mailbox_password", Description: "Change mailbox password", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in SetMailboxPasswordIn) (*mcp.CallToolResult, any, error) {
				if r := vMinLen("password", in.Password, 12); r != nil {
					return r, nil, nil
				}
				path := "/mailboxes/" + url.PathEscape(in.MailboxId) + "/password"
				body := map[string]any{}
				body["password"] = in.Password
				preview := "Destructive, irreversible — Change mailbox password. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPut, path, body})
			})
	}
	{
		type RestoreBackupIn struct {
			panelArg
			dryRunArg
			confirmArg
			BackupId string `json:"backup_id" jsonschema:"the backup's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "restore_backup", Description: "Restore a snapshot", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in RestoreBackupIn) (*mcp.CallToolResult, any, error) {
				path := "/me/backups/" + url.PathEscape(in.BackupId) + "/restore"
				preview := "Destructive, irreversible — Restore a snapshot. Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPost, path, nil})
			})
	}
}
