// Code generated by cmd/gen-tools from openapi.yaml + admin-tools.yaml. DO NOT EDIT.

package tools

import (
	"context"
	"net/http"
	"net/url"

	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/shukiv/jabali-mcp/internal/client"
)

func registerAdminRead(s *mcp.Server, reg *client.Registry) {
	{
		type AdminListUsersIn struct {
			panelArg
			Page     int    `json:"page,omitempty" jsonschema:"page number (1-based)"`
			PageSize int    `json:"page_size,omitempty" jsonschema:"results per page"`
			Q        string `json:"q,omitempty" jsonschema:"search filter"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_list_users", Description: "List all panel users (admin)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminListUsersIn) (*mcp.CallToolResult, any, error) {
				path := "/users"
				path += listQuery(in.Page, in.PageSize, in.Q)
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type AdminGetSettingsIn struct {
			panelArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_get_settings", Description: "Read server-wide settings (admin)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminGetSettingsIn) (*mcp.CallToolResult, any, error) {
				path := "/admin/settings"
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
	{
		type AdminGetUpdateStatusIn struct {
			panelArg
			Since string `json:"since,omitempty" jsonschema:"RFC 3339 time to read the log from, e.g. the run's started_at (default: 15 minutes ago)"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_get_update_status", Description: "Read the state and log of the `jabali update` run (admin)", Annotations: roAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminGetUpdateStatusIn) (*mcp.CallToolResult, any, error) {
				path := "/admin/updates/jabali/status"
				q := url.Values{}
				if in.Since != "" {
					q.Set("since", in.Since)
				}
				if enc := q.Encode(); enc != "" {
					path += "?" + enc
				}
				return runRead(ctx, reg, in, reqSpec{http.MethodGet, path, nil})
			})
	}
}

func registerAdminWrite(s *mcp.Server, reg *client.Registry) {
	{
		type AdminCreateUserIn struct {
			panelArg
			dryRunArg
			Email     string `json:"email,omitempty" jsonschema:"optional contact address"`
			IsAdmin   *bool  `json:"is_admin,omitempty" jsonschema:"is admin"`
			NameFirst string `json:"name_first,omitempty" jsonschema:"name first"`
			NameLast  string `json:"name_last,omitempty" jsonschema:"name last"`
			PackageId string `json:"package_id,omitempty" jsonschema:"hosting package ID"`
			Password  string `json:"password" jsonschema:"at least 12 characters (the panel accepts 10; this tool asks for more)"`
			Username  string `json:"username,omitempty" jsonschema:"login and Linux account name: a lowercase letter or _ first, then up to 31 of a-z 0-9 _ -. Omit to derive it from the email's local part"`
		}
		schema := inferSchema[AdminCreateUserIn]()
		schema.Properties["password"].MinLength = iptr(12)
		mcp.AddTool(s, &mcp.Tool{Name: "admin_create_user", Description: "Create a panel user (admin)", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminCreateUserIn) (*mcp.CallToolResult, any, error) {
				if r := vMinLen("password", in.Password, 12); r != nil {
					return r, nil, nil
				}
				path := "/users"
				body := map[string]any{}
				if in.Email != "" {
					body["email"] = in.Email
				}
				if in.IsAdmin != nil {
					body["is_admin"] = *in.IsAdmin
				}
				if in.NameFirst != "" {
					body["name_first"] = in.NameFirst
				}
				if in.NameLast != "" {
					body["name_last"] = in.NameLast
				}
				if in.PackageId != "" {
					body["package_id"] = in.PackageId
				}
				body["password"] = in.Password
				if in.Username != "" {
					body["username"] = in.Username
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, body})
			})
	}
	{
		type AdminUpdateSettingsIn struct {
			panelArg
			dryRunArg
			DefaultDnsTtl *int   `json:"default_dns_ttl,omitempty" jsonschema:"Server-wide default TTL for new DNS records (seconds)."`
			Hostname      string `json:"hostname,omitempty" jsonschema:"hostname"`
		}
		schema := inferSchema[AdminUpdateSettingsIn]()
		schema.Properties["default_dns_ttl"].Minimum = f64(60)
		schema.Properties["default_dns_ttl"].Maximum = f64(86400)
		mcp.AddTool(s, &mcp.Tool{Name: "admin_update_settings", Description: "Update server-wide settings (admin)", Annotations: additiveAnno(), InputSchema: schema},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminUpdateSettingsIn) (*mcp.CallToolResult, any, error) {
				if in.DefaultDnsTtl != nil {
					if r := vMin("default_dns_ttl", *in.DefaultDnsTtl, 60); r != nil {
						return r, nil, nil
					}
					if r := vMax("default_dns_ttl", *in.DefaultDnsTtl, 86400); r != nil {
						return r, nil, nil
					}
				}
				path := "/admin/settings"
				body := map[string]any{}
				if in.DefaultDnsTtl != nil {
					body["default_dns_ttl"] = *in.DefaultDnsTtl
				}
				if in.Hostname != "" {
					body["hostname"] = in.Hostname
				}
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPatch, path, body})
			})
	}
	{
		type AdminRunUpdatesIn struct {
			panelArg
			dryRunArg
			confirmArg
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_run_updates", Description: "Trigger `jabali update` (admin)", Annotations: destructiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminRunUpdatesIn) (*mcp.CallToolResult, any, error) {
				path := "/admin/updates/jabali/run"
				preview := "Destructive, irreversible — Trigger `jabali update` (admin). Target: " + path
				return runWrite(ctx, reg, in, true, preview, reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type AdminRenewSslIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_renew_ssl", Description: "Force-renew a domain's certificate (admin)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminRenewSslIn) (*mcp.CallToolResult, any, error) {
				if in.DomainId == "." || in.DomainId == ".." {
					return errResult("invalid domain_id: dot segments are not allowed"), nil, nil
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl/renew"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
	{
		type AdminRetrySslIn struct {
			panelArg
			dryRunArg
			DomainId string `json:"domain_id" jsonschema:"the domain's ULID"`
		}
		mcp.AddTool(s, &mcp.Tool{Name: "admin_retry_ssl", Description: "Retry a failed certificate issuance (admin)", Annotations: additiveAnno()},
			func(ctx context.Context, _ *mcp.CallToolRequest, in AdminRetrySslIn) (*mcp.CallToolResult, any, error) {
				if in.DomainId == "." || in.DomainId == ".." {
					return errResult("invalid domain_id: dot segments are not allowed"), nil, nil
				}
				path := "/domains/" + url.PathEscape(in.DomainId) + "/ssl/retry"
				return runWrite(ctx, reg, in, false, "", reqSpec{http.MethodPost, path, nil})
			})
	}
}
